### ISSUE TITLE
Is AE2FC never considered?

### ISSUE THREAD

**Issue by ChromaPIE** [Nomi-CEu/Nomi-CEu#1008]
### Nomi CEu Version

Nightly

### Launcher

(not related)

### Configurations or Mods Changed

(not related)

### Environment

(not related)

### Mode

Normal Mode

### Related Problem

EDIT: I noticed that the compat recipes are already in the pack. so its actually optional alright.

I did a rough search through the issue and PR but failed to find even a small bit of mentioning about add AE2 Fluid Crafting. Maybe there are already a lot of discussions around this on Discord tho. 

I do respect the decisions of permanently excluding a certain mod out of the might-add list but is there a specific reason for this mod?

### Your Solution

/

### How Will Your Solution Work

/

**Comment by IntegerLimit** [comment]
Due to focus of being beginner friendly, we have decided to not include AE2FC, although you can add it yourself, and the recipes will be adjusted accordingly.

This is due of the tendency of AE2FC to push beginners to auto craft nearly everything, a bad practice, in cases where they should learn to passive instead.
