### ISSUE TITLE
Icons on drawers are gone after updated to 1.6.1

### ISSUE THREAD

**Issue by Krydax** [Nomi-CEu/nomi-ceu#340]
![2023-04-24_16 39 57](https://user-images.githubusercontent.com/93162034/234112780-7137380a-7a39-4edc-9a48-8dddb019cfd4.png)

As you can see, none of the icons are showing, all 20 drawer slots are full in game. Breaking and then re-putting down the drawer does not fix it.

**Comment by Krydax** [comment]
Strange. Just loaded game up again and now they're back. Issue seems to have resolved after a restart?

**Comment by IntegerLimit** [comment]
This could be due to the GT drawers fix I implemented, but that should only affect TOP... probably a case of a bad install.

Also, please use the bug report template in the future. If this issue happens again, feel free to comment on this issue, and I or @Folanlron will re-open this for further investigation.
