### ISSUE TITLE
Copper in stone dust line

### ISSUE THREAD

**Issue by tturlin** [Nomi-CEu/Nomi-CEu#407]
### Nomi CEu Version

1.6.1-beta-3a

### Related Problem

Always mining copper till T3 Micro Miner in Hard Mode is kinda boring.

### Your Solution

It could be added as an output inside the early step of the stone residue line.

### How Will Your Solution Work

Adding a small amount of sulfuric copper when centrifuging metal mixture dust could fix it pretty easily

### Alternatives You've Considered

No other idea for the moment

**Comment by Emiuna** [comment]
Copper can come from t2 mm too though?

**Comment by tturlin** [comment]
Yeah, but what I mean is that is still EV tier minimum while you need mass of it before.

**Comment by Emiuna** [comment]
I feel like the amount you get from a couple tetrahedrite veins in the nether is more than enough until then but thats just my thoughts, I'll leave it to actual devs ofc

**Comment by IntegerLimit** [comment]
> I feel like the amount you get from a couple tetrahedrite veins in the nether is more than enough until then but thats just my thoughts, I'll leave it to actual devs ofc

You are probably a better responder than me, as I haven't played HM... and you have.

**Comment by Emiuna** [comment]
Oh I guess thats true lol. In my experience i only had to mine 2-3 tetrahedrite veins until getting t2 mm, and even then had a fairly big excess of copper, mostly thanks to having set up HV ore proc. Thinking about it now though, I did struggle with copper between getting my first hotu and stabilizing t3, so I do think adding copper to taranium line would be a good idea overall. Probably to a later step though, like whatever one gives lead-zinc solution, so that players are still incentivized to use a miner on tetrahedrite early on (Otherwise you can easily get passive copper early on which I feel is too close to the DML mindset).

**Comment by IntegerLimit** [comment]
> Oh I guess thats true lol. In my experience i only had to mine 2-3 tetrahedrite veins until getting t2 mm, and even then had a fairly big excess of copper, mostly thanks to having set up HV ore proc. Thinking about it now though, I did struggle with copper between getting my first hotu and stabilizing t3, so I do think adding copper to taranium line would be a good idea overall. Probably to a later step though, like whatever one gives lead-zinc solution, so that players are still incentivized to use a miner on tetrahedrite early on (Otherwise you can easily get passive copper early on which I feel is too close to the DML mindset).

Sounds Good!

**Comment by Emiuna** [comment]
Ok here's a more specific idea after talking with FolanIron:

The chem bath plat group sludge step of platline gives plat sludge residue, and the residue gives copper instead of gold (meets earlygame copper needs) (Credit to FolanIron for idea)

And then in the oxidized residue centrifuge step you get 2 buckets of sulfuric copper solution

**Comment by IntegerLimit** [comment]
> Ok here's a more specific idea after talking with FolanIron:
> 
> The chem bath plat group sludge step of platline gives plat sludge residue, and the residue gives copper instead of gold (meets earlygame copper needs) (Credit to FolanIron for idea)
> 
> And then in the oxidized residue centrifuge step you get 2 buckets of sulfuric copper solution

Would that starve Gold? (I can't join the discussion on Discord at the moment)

**Comment by Folanlron** [comment]
On HM For some odd reason, we can't process the Sludge Residue as gold at all..

With Nether/End Ores giving dbl products honestly gold isn't a problem.

But Copper is a huge problem, and has always been a problem.

**Comment by Emiuna** [comment]
Platline doesn't even usually give plat sludge resudie in hard mode, so you normally don't get any gold from it

**Comment by Emiuna** [comment]
The suggestion was to not just replace gold with copper in the recipe but also to add plat sludge residue to the chem bath aqua regia step

**Comment by Emiuna** [comment]
The chem bath aqua regia step is already a custom recipe (Changed from the nm step which just gives all the platline residues) so maybe the exclusion of plat sludge residue was an accident idk

**Comment by IntegerLimit** [comment]
I see. What does Plat Sludge Residue give? And isn't platline quite late in the game?

**Comment by Emiuna** [comment]
Plat sludge residue normally centrifuges to 2 silicon dioxide and 3 gold (for 5 residue). You can make the start of platline (platinum and palladium or even just platinum if you want) pretty easily at HV and assuming the residue is added to the aqua regia step it'll need very little infrastructure overall

**Comment by IntegerLimit** [comment]
Ok, sounds good!
