### ISSUE TITLE
Assembly Line can't craft Flux-Infused Jetplate

### ISSUE THREAD

**Issue by BlazeHunterVN1610** [Nomi-CEu/Nomi-CEu#518]
### Nomi CEu Version

1.7-alpha-1

### Launcher

Prism Launcher

### Configurations or Mods Changed

Added:
CompactMachine
GTFO 1.10.0.2
AE2 Fluid Crafting 2.4.32-r
Flux Network 4.1.1.34
ProjectRed Illumination 4.9.4.120

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

Assembly Lines can't craft Flux-Infused Jetplate, even though all ingredient are presented, items NBT are the same and in correct order:

https://github.com/Nomi-CEu/Nomi-CEu/assets/111768452/26301132-21df-49cd-abc9-3b3366e5ec87

I replace the Flux-Infused Chestplate and Resonant Jetpack with the charged ones, change the capacitor with the one that has lore, I try different version of Luv Circuit, replace the Optical Data Reception Hatch with the Data Access Hatch and put the Data Orb in (I even try the creative hatch), but nothing happen

### Expected Behavior

Assembly Lines crafts the jetplate

### Reproduction Steps

1. Put all input item in correct order, input the fluid and energy
2. Put the researched Data Orb inside the Data Access Hatch, or put the Data Orb inside a Data Bank and connect the bank to the Assembly Line
3. Nothing happen

**Comment by a-a-GiTHuB-a-a** [comment]
Does this happen with other Assembly-Line items, or just this one?

**Comment by wrulfy** [comment]
I have the same issue. This happens with both the Flux-infused and Dark Soularium Jetplates.
If you use capacitors without lore, and an armored jetpack obtained directly though the /give command it works, because then both of these items will be lacking NBT data that prevents the craft.

When you craft a fresh armored jetpack, or give youself one though JEI, it has the nbt tags "Energy:0" and "JetpackParticleType:0".
However, if you use the /give command, it lacks the energy:0 tag, just like the one in the recipe, so it crafts.

if the groovy script assembly_line.groovy can accept nbt tags added to the ingredients, it could potentially fix this issue.

this is the jetpack obtained though /give command:
![2024-02-01_18 54 45](https://github.com/Nomi-CEu/Nomi-CEu/assets/19495437/ecffdae9-e87b-4aeb-bd50-5b913d1cc289)

this is the jetpack obtained normally though crafting:
![2024-02-01_18 54 48](https://github.com/Nomi-CEu/Nomi-CEu/assets/19495437/32f3020a-9709-420b-a46b-af2b67424c53)

**Comment by wrulfy** [comment]
I have the same issue. This happens with both the Flux-infused and Dark Soularium Jetplates.
If you use capacitors without lore, and an armored jetpack obtained directly though the /give command it works, because then both of these items will be lacking NBT data that prevents the craft.

When you craft a fresh armored jetpack, or give youself one though JEI, it has the nbt tags "Energy:0" and "JetpackParticleType:0".
However, if you use the /give command, it lacks the energy:0 tag, just like the one in the recipe, so it crafts.

if the groovy script assembly_line.groovy can accept nbt tags added to the ingredients, it could potentially fix this issue.

this is the jetpack obtained though /give command:
![2024-02-01_18 54 45](https://github.com/Nomi-CEu/Nomi-CEu/assets/19495437/ecffdae9-e87b-4aeb-bd50-5b913d1cc289)

this is the jetpack obtained normally though crafting:
![2024-02-01_18 54 48](https://github.com/Nomi-CEu/Nomi-CEu/assets/19495437/32f3020a-9709-420b-a46b-af2b67424c53)


After further testing, I found out that the Flux-infused chestplate also suffers with the same NBT issues. However I don't see any difference with a freshly crafted one and one obtained though the give command, although they appear as different items in a ME network

**Comment by a-a-GiTHuB-a-a** [comment]
So it is once again an NBT issue, like the Data Orb one. Hopefully it'll be fixed in the Groovy update.
