### ISSUE TITLE
Tier Nine Micro Miner Mission

### ISSUE THREAD

**Issue by TimothyNardi** [Nomi-CEu/Nomi-CEu#546]
### Nomi CEu Version

1.7-alpha-1

### Related Problem

I think the Tier Nine Micro Miner Neutronium Mission is rather useless.

In normal Nomifactory, or at least when I previously played it, I think there was an argument for it due to the cost of Naquadria, which I remember only being obtainable through either the Mixer recipe or the Fusion Recipe. Both were doable, but of considerable expense. In CEU, normal mode, the Naquadah processing line makes Naquadria much cheaper. Perhaps this is due to the number of missions sent for Trinium, but I've been swimming in all three products. And with Americium being dirt cheap, should you build a tier three reactor Neutronium is readily available, to the point that I've considered making turbines out of it. 

Furthermore, while this is dependent on having a tier three reactor, I found the cost of the reactor to be more than worth while when considering the Overclock, Einsteinium Recipe, and Neutronium Recipe, which when taken together can lower crafting times and eliminate the need for at least a dozen microminer missions of various tiers.

### Your Solution

I would change the mission reward from Neutronium to Chaos Shards. Or rather some higher material that is then broken down into Chaos Shards.

Given the crafting requirements to create the T9, I do not believe it invalidates the T8, as it requires at least 9 T8 Missions to be sent to craft the T9. It also has the benefit of significantly reducing the Diamond load in late game, as while it is not difficult to get the diamonds with the multiblock sifter and T4s, it is kind of time consuming and produces an obscene quantity of dust in addition to the gems. 

### How Will Your Solution Work

The way I have imagined it would be obtaining some remnant star core or something, which would then be broken down continuously. Chemically or Physically. The process that came to mind, though I admit to have not put much thought into it, was utilizing a high tier, ZPM or UV, Forge Hammer to break it down into "manageable" chunks that could then be macerated, washed, and then sifted, again of high tier. This method might provide a chance output for shards of all sizes that could then synthesize a number of Chaos Shards. Perhaps the ore processing process could provide an alternative method of obtaining some other materials only obtainable through fusion like darmstadtium or duranium. Or maybe some other, new material for end game. I would also pull any dragon eggs in the reward, as I don't think it suits the item text.

The mission itself would still have chaos lair data as well as some other ingredients like stellar creation data, and perhaps a mission with improved yield or a key component could be created for the T8. Ultimately, I find the mission rather irrelevant as neutronium was available in 1/4 the quantity with some other useful products in the T8 mission and Chaos Shards felt like the most suitable alternative reward. Something useful and perhaps cost/time effective.

### Alternatives You've Considered

N/A

**Comment by Folanlron** [comment]
The Neutronium T9 mission is actually a hold-over from Omni/Nomifactory(CE Edition), as the fusion reactors in that version do not overclock at all, and it is a 35-40hour wait for Mk3 Reactors(at 2 of them) to make enough Neut for 1 T10..

The Naq in CEu is different as there is an actual Naquadah Processing Line that produces more then just the 3 flavors of Naq, (Trinium,Gallium,Titanium, and Indium can also be obtained from it) all are important byproducts from the line which is why you see it not being as much of a problem as it is in CE.

As far as Chaos shards .. I'm pretty sure people, don't want to play RNG'fest for 1 Item that is used so much in both modes of the pack, at end game. (A hint it is 350 Hearts alone required for the Infinity Ingot Costs, on the CQC in HM.) That doesn't include the Chaos cost needed to make the hearts into Infinity Ingots, it adds up pretty fast. It is at the end of the pack and really when people are going for the end, why make them wait, even longer?

**Comment by IntegerLimit** [comment]
The amount of Neutronium has been increased x2.5 for Normal Mode in dev (https://github.com/Nomi-CEu/Nomi-CEu/pull/653).

**Comment by IntegerLimit** [comment]
(The PR was actually in alpha-3, not dev, my apologies)
