### ISSUE TITLE
Processing Array inside Sterilized Cleanroom stops working on world reload

### ISSUE THREAD

**Issue by minghinshi** [Nomi-CEu/Nomi-CEu#844]
### Nomi CEu Version

1.7-beta-5c

### Launcher

Prism Launcher

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

When the world is reloaded, a processing array I built inside a sterilized cleanroom would stop working, even though it has everything needed to process the inputs. If I take out the fluid heater from the processing array's interface and put it back in, it starts working. However, the processing array would stop the next time the world is loaded.

### Expected Behavior

The processing array should continue running after world reload.

### Reproduction Steps

https://github.com/user-attachments/assets/4522184b-6bc8-4163-b4a4-2f5b43a13c38

1. Load the world. The processing array is not working.
2. Take out the fluid heater and put it back in. The processing array starts working.
3. Save and exit.
4. Load the world again. The processing array is not working.

To narrow down the cause of the bug, I performed the above steps under different conditions:

- In a processing array in a sterilized cleanroom in a new world.
- In a processing array in a new sterilized cleanroom in the original save.
- In a processing array in the bugged sterilized cleanroom in the original save.
- After breaking and replacing the processing array block (shown towards end of the video).

The bug cannot be reproduced in any of these conditions, so the bug likely has to do with the existing processing array.
The save can be downloaded here: https://drive.google.com/file/d/1To5U0i-7smnfdLAx3Kv6Ztg_lQuRgpOD/view?usp=sharing

### Additional Information

- The bug already existed when the save was on version 1.6.x.
- Apart from the processing array with the fluid heater, nearby processing arrays also suffer from the same problem.
- This bug seems similar to #549.

**Comment by IntegerLimit** [comment]
There are actually two issues here, both stemming from the same core issue. I have fixed both in Labs 0.8.3, and here are the reproduction steps.

For the issue listed above, where PAs would not work after world reload, the method found to reproduce this issue was:
1. Make a Plascrete Floor
2. Build an Advanced PA (MUST PLACE CONTORLLER)
3. *Save and Quit the World* (Step may not be needed)
4. Finish off the cleanroom, & place the cleanroom controller (IMPORTANT: Must Be Placed after STEP 5)
5. Wait until cleanroom is clean, validate that PA runs. Quit world, rejoin, PA is no longer running.

This issue seems to happen if the cleanroom controller is loaded AFTER the PA's first recipe search, causing a lack of sync between the cleanroom state of the PA multiblock and the internal meta tile entity, which handles the logic.

A seperate issue that also exists due to this syncing issue can be simply reproduced by breaking and re-placing a PA controller in a cleanroom. When the PA forms again, it will not run until you remove and then re-insert the items in the Machine Access Interface.
